
Grauman = {'Exec_PASCAL_Ferrari_Grauman_1','Exec_PASCAL_Ferrari_Grauman_2',...
    'Exec_PASCAL_Ferrari_Grauman_3','Exec_PASCAL_Ferrari_Grauman_4', ...
    'Exec_PASCAL_Ferrari_Grauman_5'};
CNN_Refill = {'Exec_PASCAL_Ferrari_CNN_Refill_1', 'Exec_PASCAL_Ferrari_CNN_Refill_2', ...
    'Exec_PASCAL_Ferrari_CNN_Refill_3', 'Exec_PASCAL_Ferrari_CNN_Refill_4', ...
    'Exec_PASCAL_Ferrari_CNN_Refill_5'};
CNN_Refill_ObjVSNoObj = {'Exec_PASCAL_Ferrari_ObjVSNoObj_CNN_Refill_1', ...
    'Exec_PASCAL_Ferrari_ObjVSNoObj_CNN_Refill_2', 'Exec_PASCAL_Ferrari_ObjVSNoObj_CNN_Refill_3', ...
    'Exec_PASCAL_Ferrari_ObjVSNoObj_CNN_Refill_4', 'Exec_PASCAL_Ferrari_ObjVSNoObj_CNN_Refill_5'};

% Test variables
tests = {'Grauman', 'CNN_Refill', 'CNN_Refill_ObjVSNoObj'};

% List of classes appearing in the object discovery
classes_list = {'tvmonitor','train','person','boat','horse','cow','bottle', ...
    'dog','aeroplane','car','bus','bicycle','chair','diningtable','pottedplant', ...
    'bird','cat','motorbike','sheep','sofa'};
